name: homework_solver
description: Homework solver

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11
  google_mlkit_barcode_scanning: ^0.5.0
  google_mlkit_commons: ^0.2.0
  google_mlkit_language_id: ^0.5.0
  google_mlkit_text_recognition: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
